name: backlog_manager_excel
description: A CLI tool to manage project items using an Excel file.
version: 1.0.0
# repository: https://github.com/your_username/backlog_manager_excel

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  excel: ^4.0.1 # For reading/writing .xlsx files
  path: ^1.9.0
  uuid: ^4.3.3 # For generating unique IDs
  intl: ^0.19.0 # For date formatting
  tabular: ^0.6.3+1 # For formatting list output nicely

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4
